base/urls.py
from django.urls import path
from .chatbot.chat_view import chat
from .views import *


app_name = 'base'

urlpatterns = [
    path("", index, name="index"),
    path("search", search, name="search"),
    path('event/<int:event_id>', event_detail, name='event_detail'),
    path('event_registration/<int:event_id>', event_registration, name='event_registration'),
    path('events/<int:event_id>/rate/', rate_event, name='rate_event'),
    path('chat/', chat, name='chat'),
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path("", index, name="index"),
    path("events/", events, name="events"),
    path("event/<int:event_id>", event_settings, name="event_settings"),
    path('event/<int:event_id>/approve/', approve_event, name='approve_event'),
    path('event/<int:event_id>/archive/', archive_event, name='archive_event'),
    path('event/<int:event_id>/unarchive/', unarchive_event, name='unarchive_event'),
    path('event/<int:event_id>/delete/', delete_event, name='delete_event'),
    path('event/<int:event_id>/gallery/add/', add_gallery_images, name='add_gallery_images'),
    path('gallery/image/<int:image_id>/delete/', delete_gallery_image, name='delete_gallery_image'),
    path("users/", users, name="users"),
]

eigsi_events/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from dashboard.views import auth, access_denied

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('auth/', auth, name='auth'),
    path('access_denied/', access_denied, name='access_denied'),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(next_page=''), name='logout'),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms
from django.forms import ClearableFileInput
from dashboard.models import Event, EventGallery


class NewEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'location', 'is_public', 'event_type', 'poster']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Titre de l\'évènement'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description'}),
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'location': forms.TextInput(attrs={'placeholder': 'Lieu'}),
            'event_type': forms.Select(),
            'is_public': forms.CheckboxInput(),
            'poster': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput(attrs={
            'class': 'sr-only',
            'accept': 'image/*'
        }))
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class EventGalleryForm(forms.ModelForm):
    images = MultipleFileField(
        label='Images',
        required=False
    )

    class Meta:
        model = EventGallery
        fields = ['images']

    def clean_images(self):
        images = self.cleaned_data.get('images')
        if images:
            for image in images:
                if not image.content_type.startswith('image'):
                    raise forms.ValidationError("Un des fichiers n'est pas une image.")
        return images

dashboard/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from dashboard.forms import NewEventForm, EventGalleryForm
from dashboard.models import Event, EventGallery, Operation, Participation
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib import messages
from django.utils import timezone
from dashboard.operation_types import OperationTypes

now = timezone.now()

event_type = [
    ('conference', 'Conférence'),
    ('workshop', 'Atelier'),
    ('cultural', 'Culturel'),
    ('ftour', 'Ftour'),
    ('competition', 'Compétition'),
    ('charity', 'Caritatif'),
    ('talent_show', 'Eigsi Got Talent'),
    ('integration_day', 'Journée d\'intégration'),
    ('other', 'Autres'),
]

def is_admin(user):
    return user.groups.filter(name='Admin').exists()

def is_super_admin(user):
    return user.groups.filter(name='SuperAdmin').exists()

def is_authorized(user):
    print(f"{user.username} {is_admin(user)} and {is_super_admin(user)}")
    return is_admin(user) or is_super_admin(user)

def auth(request):
    if request.user.is_authenticated:
        if is_authorized(request.user):
            return redirect(request.GET.get('next', 'dashboard/index'))
        return redirect(request.GET.get('next', '/'))

    if request.method == 'GET' and 'error' in request.GET:
        messages.error(request, "Erreur lors de la connexion. Veuillez réessayer.")

    return render(request, 'auth.html')


def access_denied(request):
    return render(request, 'access_denied.html')


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def index(request):
    upcoming_events = Event.objects.filter(date__gte=now, archived_at=None, status=True).count()
    pending_events = Event.objects.filter(status=False, archived_at=None).count()
    all_events = Event.objects.count()
    recent_activities = Operation.objects.all().order_by('-date_time')

    operation_type_titles = [
        ('added_event', "Évènement ajouté"),
        ('updated_event', "Évènement modifié"),
        ('approved_event', "Évènement approuvé"),
        ('archived_event', "Évènement archivé"),
        ('unarchived_event', "Évènement désarchivé"),
        ('deleted_event', "Évènement supprimé"),
        ('updated_gallery', "Galerie modifié"),
        ('add_user', "Utilisateur ajouté"),
        ('activate_user', "Utilisateur activé"),
        ('deactivate_user', "Utilisateur désactivé"),
        ('delete_user', "Utilisateur supprimé"),
    ]

    context = {'upcoming_events': upcoming_events, 'pending_events': pending_events,
               'all_events': all_events, 'recent_activities': recent_activities,
               'operation_type_titles': operation_type_titles, 'now': now}

    return render(request, 'dashboard/index.html', context)


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def events(request):
    if request.method == 'POST':
        form = NewEventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save()
            Operation.objects.create(
                author=request.user,
                type=OperationTypes.ADDED_EVENT.value,
                content_object=event
            )
            return redirect('dashboard:events')
    else:
        form = NewEventForm()

    start = 2016
    year = now.year

    search = request.GET.get('search', '')
    event_type_filter = request.GET.get('event_type', '')
    accessibility = request.GET.get('accessibility', '')
    year_filter = request.GET.get('year', '')
    page = request.GET.get('page', 1)

    event_s = Event.objects.all()

    if search:
        event_s = event_s.filter(title__icontains=search) | event_s.filter(description__icontains=search)

    if event_type_filter:
        event_s = event_s.filter(event_type=event_type_filter)

    if accessibility:
        is_public = accessibility == 'public'
        event_s = event_s.filter(is_public=is_public)

    if year_filter:
        event_s = event_s.filter(date__year=year_filter)

    paginator = Paginator(event_s, 15)
    try:
        events_page = paginator.page(page)
    except PageNotAnInteger:
        events_page = paginator.page(1)
    except EmptyPage:
        events_page = paginator.page(paginator.num_pages)

    has_events = len(event_s) != 0
    years = list(range(year, start - 1, -1))

    context = {
        'has_events': has_events,
        'events': events_page,
        'start': start,
        'years': years,
        'event_type': event_type,
        'now': now,
        'search': search,
        'event_type_filter': event_type_filter,
        'accessibility': accessibility,
        'year_filter': year_filter
    }

    return render(request, 'dashboard/events.html', context)


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def event_settings(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    has_stats = event.date < now

    if request.method == 'POST':
        form = NewEventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            Operation.objects.create(
                author=request.user,
                type=OperationTypes.UPDATED_EVENT.value,
                content_object=event
            )
            return redirect('dashboard:event_settings', event_id=event.id)
    else:
        form = NewEventForm(instance=event)

    context = {
        'event': event,
        'has_stats': has_stats,
        'form': form,
        'is_super_admin': request.user.groups.filter(name="SuperAdmin").exists()
    }

    return render(request, 'dashboard/event_settings/event_settings.html', context)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def approve_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event.status = True
        event.save()
        Operation.objects.create(
            author=request.user,
            type=OperationTypes.APPROVED_EVENT.value,
            content_object=event
        )
        messages.success(request, "L'événement a été approuvé avec succès.")
        return redirect('dashboard:event_settings', event_id=event_id)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def archive_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event.archived_at = now
        event.save()
        Operation.objects.create(
            author=request.user,
            type=OperationTypes.ARCHIVED_EVENT.value,
            content_object=event
        )
        messages.success(request, "L'événement a été bien archivé.")
        return redirect('dashboard:event_settings', event_id=event_id)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def unarchive_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event.archived_at = None
        event.save()
        Operation.objects.create(
            author=request.user,
            type=OperationTypes.UNARCHIVED_EVENT.value,
            content_object=event
        )
        messages.success(request, "L'événement a été bien désarchivé.")
        return redirect('dashboard:event_settings', event_id=event_id)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def delete_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event_title = event.title

        if not request.user.groups.filter(name="SuperAdmin").exists():
            messages.error(request, "Vous n'avez pas les droits pour supprimer un événement.")
            return redirect('dashboard:event_settings', event_id=event_id)

        try:
            event.delete()
            Operation.objects.create(
                author=request.user,
                type=OperationTypes.DELETED_EVENT.value,
                content_title=event_title
            )
            messages.success(request, "L'événement a été supprimé avec succès.")
            return redirect('dashboard:events')

        except Exception as e:
            messages.error(request, "Une erreur est survenue lors de la suppression de l'événement.")
            return redirect('dashboard:event_settings', event_id=event_id)

    return JsonResponse({'status': 'error', 'message': 'Méthode non autorisée'}, status=405)


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def add_gallery_images(request, event_id):
    event = get_object_or_404(Event, id=event_id)

    if request.method == 'POST':
        form = EventGalleryForm(request.POST, request.FILES)
        if form.is_valid():
            images = request.FILES.getlist('images')
            gallery_images = []

            for image in images:
                gallery_image = EventGallery.objects.create(
                    event=event,
                    image=image
                )
                gallery_images.append({
                    'id': gallery_image.id,
                    'url': gallery_image.image.url
                })

            return JsonResponse({
                'status': 'success',
                'images': gallery_images
            })
        else:
            return JsonResponse({
                'status': 'error',
                'errors': form.errors
            }, status=400)

    return JsonResponse({'status': 'error', 'message': 'Requête invalide'}, status=405)


@login_required

templates/dashboard/event_settings/event_settings.html
{% extends 'dashboard/base_dashboard.html' %}
{% load static %}
{% block content %}
    <div class="w-full h-full overflow-hidden">
        <div class="flex-1 flex flex-col h-full">
            <div class="flex flex-col w-full gap-1 md:gap-2 mb-2 px-6 pt-4 md:px-8 md:pt-6">
                <div class="w-full text-xs flex flex-row flex-nowrap gap-1 items-center line-clamp-1 overflow-ellipsis">
                    <a href="{% url 'dashboard:events' %}" class="text-[#a1c617] hover:underline">Évènements</a>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="0.75" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-chevron-right">
                        <path d="m9 18 6-6-6-6"/>
                    </svg>
                    <div class="w-full line-clamp-1 overflow-ellipsis">{{ event.title }}</div>
                </div>
                <div id="tab-bar"
                     class="relative w-full flex flex-row flex-nowrap items-center text-sm border-b select-none">
                    <div id="generalTabBtn" class="px-2 py-1 rounded hover:bg-[#f5fccb] cursor-pointer">Général</div>
                    <div id="galleryTabBtn" class="px-2 py-1 rounded hover:bg-[#f5fccb] cursor-pointer">Galerie</div>
                    <div id="statsTabBtn" class="px-2 py-1 rounded hover:bg-[#f5fccb] cursor-pointer">Stats</div>
                    <div id="slider"
                         class="absolute h-[2px] bottom-[-1px] bg-[#a1c617] transition-all ease-in-out duration-300"></div>
                </div>
            </div>
            <div class="h-full overflow-hidden">
                <div class="h-full overflow-y-auto px-6 pb-6 md:px-8 md:pb-8">
                    {# general tab #}
                    {% include 'dashboard/event_settings/general_tab.html' with event=event %}
                    {# gallery tab #}
                    {% include 'dashboard/event_settings/gallery_tab.html' with event=event %}
                    {# stats tab #}
                    {% include 'dashboard/event_settings/stats_tab.html' with event=event %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script_tags %}
    <script src="{% static 'js/src/event_settings_scripts.js' %}"></script>
{% endblock %}

templates/dashboard/event_settings/gallery_tab.html
<div id="galleryTab" class="hidden w-full pt-3">
    <div id="gallery-counter" class="text-sm mb-3">
        {% if event.gallery.all|length == 0 %}
            Aucune image dans la galerie
        {% elif event.gallery.all|length == 1 %}
            1 image dans la galerie
        {% else %}
            {{ event.gallery.all|length }} images dans la galerie
        {% endif %}
    </div>
    {% if not event.archived_at %}
        <div class="mb-8">
            <div>
                <form id="gallery-form" method="post" enctype="multipart/form-data"
                      data-upload-url="{% url 'dashboard:add_gallery_images' event.id %}">
                    {% csrf_token %}
                    <div class="space-y-2">
                        <label for="gallery-images" class="block text-sm font-medium text-gray-700">
                                    <span class="mt-1 flex justify-center px-8 py-8 border-2 border-gray-300 border-dashed rounded-md">
                                        <div class="space-y-1 text-center flex flex-col items-center">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48"
                                                 viewBox="0 0 24 24" fill="none" stroke="rgb(156 163 175)"
                                                 stroke-width="1" stroke-linecap="round" stroke-linejoin="round"
                                                 class="lucide lucide-image-plus">
                                                <path d="M16 5h6"/>
                                                <path d="M19 2v6"/>
                                                <path d="M21 11.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7.5"/>
                                                <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>
                                                <circle cx="9" cy="9" r="2"/>
                                            </svg>
                                            <div class="flex text-sm text-gray-600 select-none">
                                                <label for="gallery-images"
                                                       class="relative cursor-pointer bg-white rounded-md font-medium text-[#80a20e] hover:text-[#a1c617] focus-within:outline-none focus-within:ring-0 focus-within:ring-offset-0">
                                                    <span>Télécharger des images</span>
                                                    <input id="gallery-images" name="images" type="file"
                                                           class="sr-only" multiple accept="image/*">
                                                </label>
                                                <p class="pl-1">ou glisser-déposer ici</p>
                                            </div>
                                        </div>
                                    </span>
                        </label>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
    <div id="gallery-container" class="relative grid grid-cols-2 md:grid-cols-4 gap-4">
        {% for image in event.gallery.all %}
            <div id="image-{{ image.id }}" class="gallery-image relative group rounded-lg overflow-hidden shadow">
                <div class="aspect-w-16 aspect-h-9">
                    <img src="{{ image.image.url }}"
                         alt=""
                         class="w-full h-full object-cover">
                </div>
                <button class="delete-image absolute top-2 right-2 p-2 rounded-full bg-red-600 hover:bg-red-700 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
                        data-image-id="{{ image.id }}"
                        aria-label="Supprimer l'image">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                         viewBox="0 0 24 24"
                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round" class="lucide lucide-trash-2">
                        <path d="M3 6h18"/>
                        <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/>
                        <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>
                        <line x1="10" x2="10" y1="11" y2="17"/>
                        <line x1="14" x2="14" y1="11" y2="17"/>
                    </svg>
                </button>
            </div>
        {% endfor %}
    </div>
    <div id="loading-indicator"
         class="hidden fixed top-0 left-0 right-0 bottom-0 w-full h-full z-50 overflow-hidden bg-gray-700 opacity-75 flex-col items-center justify-center">
        <div class="animate-spin rounded-full h-32 w-32 border-b-2 border-[#d8f165]"></div>
        <h2 class="text-center text-white text-xl font-semibold mt-4">Chargement...</h2>
        <p class="w-1/3 text-center text-white">Cela peut prendre quelques secondes, veuillez
            patienter...
        </p>
    </div>
</div>

templates/dashboard/event_settings/general_tab.html
{% load static %}
<div id="generalTab" class="w-full flex flex-col gap-2 pt-3 pb-4">
    {% if event.status is False %}
        <div class="flex flex-row flex-nowrap items-center gap-2 border-l-4 bg-orange-100 border-orange-500 p-3  w-fit mb-5">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                 viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                 stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-info">
                <circle cx="12" cy="12" r="10"/>
                <path d="M12 16v-4"/>
                <path d="M12 8h.01"/>
            </svg>
            <div class="text-sm">Cet évènement est en attente d'approbation</div>
            {% if is_super_admin %}
            	<form method="POST" action="{% url 'dashboard:approve_event' event.id %}"
                  class="d-inline">
                {% csrf_token %}
                <button type="submit"
                        class="px-3 py-2 rounded-full bg-[#4d6113] hover:bg-[#617b10] active:scale-95 duration-100 will-change text-xs text-white">
                    Approuver
                </button>
            </form>
            {% endif %}
        </div>
    {% endif %}
    {% if event.archived_at %}
        <div class="flex flex-col items-start bg-gray-100 border-gray-500 p-3 w-fit mb-5">
            <div class="text-sm">Évènement archivé le {{ event.archived_at|date:"d M Y" }}</div>
            <div class="text-sm">Désarchiver pour pouvoir y apporter des modifications</div>
            <form method="POST" action="{% url 'dashboard:unarchive_event' event.id %}"
                  class="d-inline">
                {% csrf_token %}
                <button type="submit"
                        class="mt-1 px-3 py-2 rounded-full bg-[#4d6113] hover:bg-[#617b10] active:scale-95 duration-100 will-change text-xs text-white">
                    Désarchiver
                </button>
            </form>
        </div>
    {% endif %}
    <div class="w-[100%] md:w-[430px]">
        <form id="event-form" method="POST" enctype="multipart/form-data"
              class="flex flex-col gap-4">
            {% csrf_token %}
            <label for="pick-poster">
                     <span class="flex flex-col gap-1">
                        <span class="text-xs font-bold">Affiche</span>
                        <div class="relative group rounded-lg {% if event.archived_at is None %}cursor-pointer{% endif %}">
                           {% if event.poster %}
                               <img id="poster-preview" src="{{ event.poster.url }}"
                                    alt="{{ event.title }}" class="rounded-lg w-full">
                           {% else %}
                               <img id="poster-preview"
                                    src="{% static 'images/eigsi_event_default_banner.png' %}"
                                    alt="Affiche par défaut"
                                    class="rounded-lg w-full">
                           {% endif %}
                            {% if event.archived_at is None %}
                                <div class="absolute top-2 right-2 p-2 rounded-full bg-[#80a20e] hover:bg-[#617b10] text-white opacity-0 group-hover:opacity-100 transition-opacity duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#a1c617]">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="lucide lucide-pencil">
                                        <path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/>
                                        <path d="m15 5 4 4"/>
                                    </svg>
                                </div>
                            {% endif %}
                        </div>
                     </span>
            </label>
            <input id="pick-poster" class="w-0 h-0" type="file" name="poster" {% if event.archived_at %}
                   disabled {% endif %}>
            <label class="flex flex-col gap-1">
                <span class="text-xs font-bold">Titre</span>
                <input class="form-control border-gray-300 focus:border-[#a1c617] focus:ring-0 border px-2 py-1 w-full rounded-md text-sm"
                       type="text" name="title" placeholder="Titre" value="{{ event.title }}"
                       required {% if event.archived_at %}disabled{% endif %}>
            </label>
            <label class="flex flex-col gap-1">
                <span class="text-xs font-bold">Lieu</span>
                <input class="form-control border-gray-300 focus:border-[#a1c617] focus:ring-0 border px-2 py-1 w-full rounded-md text-sm"
                       type="text" name="location" placeholder="Lieu" value="{{ event.location }}"
                       required {% if event.archived_at %}disabled{% endif %}>
            </label>
            <label class="flex flex-col gap-1">
                <span class="text-xs font-bold">Description</span>
                <textarea id="description"
                          class="form-control border-gray-300 focus:border-[#a1c617] focus:ring-0 border px-2 py-1 w-full rounded-md text-sm resize-none"
                          name="description" placeholder="Description" rows="4"
                          required {% if event.archived_at %}
                          disabled {% endif %}>{{ event.description }}</textarea>
            </label>
            <label class="flex flex-col gap-1">
                <span class="text-xs font-bold">Date et heure</span>
                <input class="form-control border-gray-300 focus:border-[#a1c617] focus:ring-0 border px-2 py-1 w-full rounded-md text-sm"
                       type="datetime-local" name="date" value="{{ event.date|date:'Y-m-d\TH:i' }}"
                       required {% if event.archived_at %}disabled{% endif %}>
            </label>
            <label class="flex flex-col gap-1">
                <span class="text-xs font-bold">Type d'évènement</span>
                <select class="form-control border-gray-300 focus:border-[#a1c617] focus:ring-0 border px-2 py-1 w-full rounded-md text-sm"
                        name="event_type" required {% if event.archived_at %}disabled{% endif %}>
                    {% for value, label in event.EVENT_TYPE_CHOICES %}
                        <option value="{{ value }}"
                                {% if event.event_type == value %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
            </label>
            <label class="flex flex-row flex-nowrap items-center gap-3 text-sm text-[#415215] w-full">
                <span class="text-xs font-bold">Public</span>
                <input class="form-control border focus:border-[#a1c617] focus:ring-0 p-1 rounded-md {% if event.archived_at is None %}cursor-pointer{% endif %}"
                       type="checkbox" name="is_public" {% if event.is_public %}checked{% endif %}
                        {% if event.archived_at %}disabled{% endif %}>
            </label>
            {% if event.archived_at is None %}
                <div class="flex flex-row flex-nowrap gap-2 w-full justify-end items-center">
                    <button id="submit-btn" type="submit"
                            class="px-3 py-2 rounded-full bg-[#4d6113] hover:bg-[#617b10] active:scale-95 duration-100 will-change text-xs text-white disabled:bg-gray-300 disabled:active:scale-100"
                            disabled>
                        Enregistrer les modifications
                    </button>
                </div>
            {% endif %}
        </form>
    </div>
    {% if event.archived_at is None and event.status %}
        <hr class="mt-6">
        <div class="rounded-md border border-gray-200 p-3 w-fit my-5">
            <div class="flex flex-col align-left">
                <div class="flex flex-row flex-nowrap items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-archive">
                        <rect width="20" height="5" x="2" y="3" rx="1"/>
                        <path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/>
                        <path d="M10 12h4"/>
                    </svg>
                    <span class="text-sm font-bold">Archiver l'événement</span>
                </div>
                <div class="text-sm mt-1">Une fois archivé, l'événement ne sera plus visible par les visiteurs.</div>
            </div>
            <form method="POST" action="{% url 'dashboard:archive_event' event.id %}"
                  class="d-inline">
                {% csrf_token %}
                <button type="submit"
                        class="mt-2 px-2 py-1 rounded-md border border-red-300 bg-red-100 text-red-500 hover:bg-red-200 active:scale-95 duration-100 will-change text-sm font-medium">
                    Archiver
                </button>
            </form>
        </div>
    {% endif %}
</div>