base/urls.py
from django.urls import path
from .chatbot.chat_view import chat
from .views import *


app_name = 'base'

urlpatterns = [
    path("", index, name="index"),
    path("search", search, name="search"),
    path('event/<int:event_id>', event_detail, name='event_detail'),
    path('event_registration/<int:event_id>', event_registration, name='event_registration'),
    path('events/<int:event_id>/rate/', rate_event, name='rate_event'),
    path('chat/', chat, name='chat'),
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path("", index, name="index"),
    path("events/", events, name="events"),
    path("event/<int:event_id>", event_settings, name="event_settings"),
    path('event/<int:event_id>/approve/', approve_event, name='approve_event'),
    path('event/<int:event_id>/archive/', archive_event, name='archive_event'),
    path('event/<int:event_id>/unarchive/', unarchive_event, name='unarchive_event'),
    path('event/<int:event_id>/delete/', delete_event, name='delete_event'),
    path('event/<int:event_id>/gallery/add/', add_gallery_images, name='add_gallery_images'),
    path('gallery/image/<int:image_id>/delete/', delete_gallery_image, name='delete_gallery_image'),
    path("users/", users, name="users"),
]

eigsi_events/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from dashboard.views import auth, access_denied

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('auth/', auth, name='auth'),
    path('access_denied/', access_denied, name='access_denied'),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(next_page=''), name='logout'),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms
from django.forms import ClearableFileInput
from dashboard.models import Event, EventGallery


class NewEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'location', 'is_public', 'event_type', 'poster']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Titre de l\'évènement'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description'}),
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'location': forms.TextInput(attrs={'placeholder': 'Lieu'}),
            'event_type': forms.Select(),
            'is_public': forms.CheckboxInput(),
            'poster': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput(attrs={
            'class': 'sr-only',
            'accept': 'image/*'
        }))
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class EventGalleryForm(forms.ModelForm):
    images = MultipleFileField(
        label='Images',
        required=False
    )

    class Meta:
        model = EventGallery
        fields = ['images']

    def clean_images(self):
        images = self.cleaned_data.get('images')
        if images:
            for image in images:
                if not image.content_type.startswith('image'):
                    raise forms.ValidationError("Un des fichiers n'est pas une image.")
        return images

dashboard/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from dashboard.forms import NewEventForm, EventGalleryForm
from dashboard.models import Event, EventGallery, Operation, Participation
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib import messages
from django.utils import timezone
from dashboard.operation_types import OperationTypes

now = timezone.now()

event_type = [
    ('conference', 'Conférence'),
    ('workshop', 'Atelier'),
    ('cultural', 'Culturel'),
    ('ftour', 'Ftour'),
    ('competition', 'Compétition'),
    ('charity', 'Caritatif'),
    ('talent_show', 'Eigsi Got Talent'),
    ('integration_day', 'Journée d\'intégration'),
    ('other', 'Autres'),
]

def is_admin(user):
    return user.groups.filter(name='Admin').exists()

def is_super_admin(user):
    return user.groups.filter(name='SuperAdmin').exists()

def is_authorized(user):
    print(f"{user.username} {is_admin(user)} and {is_super_admin(user)}")
    return is_admin(user) or is_super_admin(user)

def auth(request):
    if request.user.is_authenticated:
        if is_authorized(request.user):
            return redirect(request.GET.get('next', 'dashboard/index'))
        return redirect(request.GET.get('next', '/'))

    if request.method == 'GET' and 'error' in request.GET:
        messages.error(request, "Erreur lors de la connexion. Veuillez réessayer.")

    return render(request, 'auth.html')


def access_denied(request):
    return render(request, 'access_denied.html')


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def index(request):
    upcoming_events = Event.objects.filter(date__gte=now, archived_at=None, status=True).count()
    pending_events = Event.objects.filter(status=False, archived_at=None).count()
    all_events = Event.objects.count()
    recent_activities = Operation.objects.all().order_by('-date_time')

    operation_type_titles = [
        ('added_event', "Évènement ajouté"),
        ('updated_event', "Évènement modifié"),
        ('approved_event', "Évènement approuvé"),
        ('archived_event', "Évènement archivé"),
        ('unarchived_event', "Évènement désarchivé"),
        ('deleted_event', "Évènement supprimé"),
        ('updated_gallery', "Galerie modifié"),
        ('add_user', "Utilisateur ajouté"),
        ('activate_user', "Utilisateur activé"),
        ('deactivate_user', "Utilisateur désactivé"),
        ('delete_user', "Utilisateur supprimé"),
    ]

    context = {'upcoming_events': upcoming_events, 'pending_events': pending_events,
               'all_events': all_events, 'recent_activities': recent_activities,
               'operation_type_titles': operation_type_titles, 'now': now}

    return render(request, 'dashboard/index.html', context)


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def events(request):
    if request.method == 'POST':
        form = NewEventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save()
            Operation.objects.create(
                author=request.user,
                type=OperationTypes.ADDED_EVENT.value,
                content_object=event
            )
            return redirect('dashboard:events')
    else:
        form = NewEventForm()

    start = 2016
    year = now.year

    search = request.GET.get('search', '')
    event_type_filter = request.GET.get('event_type', '')
    accessibility = request.GET.get('accessibility', '')
    year_filter = request.GET.get('year', '')
    page = request.GET.get('page', 1)

    event_s = Event.objects.all()

    if search:
        event_s = event_s.filter(title__icontains=search) | event_s.filter(description__icontains=search)

    if event_type_filter:
        event_s = event_s.filter(event_type=event_type_filter)

    if accessibility:
        is_public = accessibility == 'public'
        event_s = event_s.filter(is_public=is_public)

    if year_filter:
        event_s = event_s.filter(date__year=year_filter)

    paginator = Paginator(event_s, 15)
    try:
        events_page = paginator.page(page)
    except PageNotAnInteger:
        events_page = paginator.page(1)
    except EmptyPage:
        events_page = paginator.page(paginator.num_pages)

    has_events = len(event_s) != 0
    years = list(range(year, start - 1, -1))

    context = {
        'has_events': has_events,
        'events': events_page,
        'start': start,
        'years': years,
        'event_type': event_type,
        'now': now,
        'search': search,
        'event_type_filter': event_type_filter,
        'accessibility': accessibility,
        'year_filter': year_filter
    }

    return render(request, 'dashboard/events.html', context)


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def event_settings(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    has_stats = event.date < now

    if request.method == 'POST':
        form = NewEventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            Operation.objects.create(
                author=request.user,
                type=OperationTypes.UPDATED_EVENT.value,
                content_object=event
            )
            return redirect('dashboard:event_settings', event_id=event.id)
    else:
        form = NewEventForm(instance=event)

    context = {
        'event': event,
        'has_stats': has_stats,
        'form': form,
        'is_super_admin': request.user.groups.filter(name="SuperAdmin").exists()
    }

    return render(request, 'dashboard/event_settings/event_settings.html', context)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def approve_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event.status = True
        event.save()
        Operation.objects.create(
            author=request.user,
            type=OperationTypes.APPROVED_EVENT.value,
            content_object=event
        )
        messages.success(request, "L'événement a été approuvé avec succès.")
        return redirect('dashboard:event_settings', event_id=event_id)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def archive_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event.archived_at = now
        event.save()
        Operation.objects.create(
            author=request.user,
            type=OperationTypes.ARCHIVED_EVENT.value,
            content_object=event
        )
        messages.success(request, "L'événement a été bien archivé.")
        return redirect('dashboard:event_settings', event_id=event_id)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def unarchive_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event.archived_at = None
        event.save()
        Operation.objects.create(
            author=request.user,
            type=OperationTypes.UNARCHIVED_EVENT.value,
            content_object=event
        )
        messages.success(request, "L'événement a été bien désarchivé.")
        return redirect('dashboard:event_settings', event_id=event_id)


@login_required
@user_passes_test(is_super_admin, login_url='access_denied', redirect_field_name=None)
def delete_event(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Event, id=event_id)
        event_title = event.title

        if not request.user.groups.filter(name="SuperAdmin").exists():
            messages.error(request, "Vous n'avez pas les droits pour supprimer un événement.")
            return redirect('dashboard:event_settings', event_id=event_id)

        try:
            event.delete()
            Operation.objects.create(
                author=request.user,
                type=OperationTypes.DELETED_EVENT.value,
                content_title=event_title
            )
            messages.success(request, "L'événement a été supprimé avec succès.")
            return redirect('dashboard:events')

        except Exception as e:
            messages.error(request, "Une erreur est survenue lors de la suppression de l'événement.")
            return redirect('dashboard:event_settings', event_id=event_id)

    return JsonResponse({'status': 'error', 'message': 'Méthode non autorisée'}, status=405)


@login_required
@user_passes_test(is_authorized, login_url='access_denied', redirect_field_name=None)
def add_gallery_images(request, event_id):
    event = get_object_or_404(Event, id=event_id)

    if request.method == 'POST':
        form = EventGalleryForm(request.POST, request.FILES)
        if form.is_valid():
            images = request.FILES.getlist('images')
            gallery_images = []

            for image in images:
                gallery_image = EventGallery.objects.create(
                    event=event,
                    image=image
                )
                gallery_images.append({
                    'id': gallery_image.id,
                    'url': gallery_image.image.url
                })

            return JsonResponse({
                'status': 'success',
                'images': gallery_images
            })
        else:
            return JsonResponse({
                'status': 'error',
                'errors': form.errors
            }, status=400)

    return JsonResponse({'status': 'error', 'message': 'Requête invalide'}, status=405)


@login_required

templates/dashboard/index.html
{% extends 'dashboard/base_dashboard.html' %}
{% load static %}
{% block content %}
    <div class="relative flex flex-row flex-nowrap w-full h-full overflow-hidden">
        <div class="flex-1 flex flex-col h-full">
            <div class="flex flex-row flex-nowrap items-center w-full justify-between mb-2 px-6 pt-4 md:px-8 md:pt-6">
                <div class="text-base md:text-xl font-bold text-[#222e05]">Tableau de bord</div>
                <div class="md:hidden">
                    <button id="openRecentActivitiesModalBtn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="lucide lucide-clock-3">
                            <circle cx="12" cy="12" r="10"/>
                            <polyline points="12 6 12 12 16.5 12"/>
                        </svg>
                    </button>
                </div>
            </div>
            <div class="h-full overflow-hidden">
                <div class="h-full overflow-y-auto px-6 pb-6 md:px-8 md:pb-8">
                    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-4 mb-5">
                        <a href="{% url 'dashboard:events' %}">
                            <div class="flex flex-col gap-2 rounded-lg p-4 bg-[#f5fccb] hover:bg-[#eaf89e] transition-colors">
                                <div class="text-sm line-clamp-1">Voir les évènements</div>
                                <div class="w-full flex flex-row justify-start">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="lucide lucide-calendar-days">
                                        <path d="M8 2v4"/>
                                        <path d="M16 2v4"/>
                                        <rect width="18" height="18" x="3" y="4" rx="2"/>
                                        <path d="M3 10h18"/>
                                        <path d="M8 14h.01"/>
                                        <path d="M12 14h.01"/>
                                        <path d="M16 14h.01"/>
                                        <path d="M8 18h.01"/>
                                        <path d="M12 18h.01"/>
                                        <path d="M16 18h.01"/>
                                    </svg>
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'dashboard:users' %}">
                            <div class="flex flex-col gap-2 rounded-lg p-4 bg-amber-100 hover:bg-amber-200 transition-colors">
                                <div class="text-sm line-clamp-1">Gérer les utilisateurs</div>
                                <div class="w-full flex flex-row justify-start">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="lucide lucide-users">
                                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/>
                                        <circle cx="9" cy="7" r="4"/>
                                        <path d="M22 21v-2a4 4 0 0 0-3-3.87"/>
                                        <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
                                    </svg>
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'dashboard:index' %}">
                            <div class="flex flex-col gap-2 rounded-lg p-4 bg-blue-100 hover:bg-blue-200 transition-colors">
                                <div class="text-sm line-clamp-1">Consulter les rapports</div>
                                <div class="w-full flex flex-row justify-start">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="lucide lucide-clipboard-minus">
                                        <rect width="8" height="4" x="8" y="2" rx="1" ry="1"/>
                                        <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/>
                                    </svg>
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'dashboard:index' %}">
                            <div class="flex flex-col gap-2 rounded-lg p-4 bg-fuchsia-100 hover:bg-fuchsia-200 transition-colors">
                                <div class="text-sm line-clamp-1">Gérer les paramètres</div>
                                <div class="w-full flex flex-row justify-start">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="lucide lucide-settings">
                                        <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/>
                                        <circle cx="12" cy="12" r="3"/>
                                    </svg>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="grid grid-cols-3 gap-4 mb-5">
                        <div class="flex flex-col gap-2 rounded-lg p-4 bg-white shadow">
                            <div class="text-sm font-bold line-clamp-1">Évènements à venir</div>
                            <div class="w-full flex flex-row justify-start text-2xl text-[#222e05]">{{ upcoming_events }}</div>
                        </div>
                        <div class="flex flex-col gap-2 rounded-lg p-4 bg-white shadow">
                            <div class="text-sm font-bold line-clamp-1">En attente</div>
                            <div class="w-full flex flex-row justify-start text-2xl text-[#222e05]">{{ pending_events }}</div>
                        </div>
                        <div class="flex flex-col gap-2 rounded-lg p-4 bg-white shadow">
                            <div class="text-sm font-bold line-clamp-1">Total évènements</div>
                            <div class="w-full flex flex-row justify-start text-2xl text-[#222e05]">{{ all_events }}</div>
                        </div>
                    </div>
                    <div class="flex flex-col gap-2 w-full mt-6">
                        <div class="text-base font-bold">Statistiques</div>
                        <div class="flex flex-col gap-3">
                            {# Stats here #}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="recentActivities"
             class="recentActivitiesHidden bg-white absolute bottom-0 left-0 right-0 mt-[20px] rounded-tl-md rounded-tr-md md:rounded-none border-x md:border-r-0 md:m-0 md:relative md:flex flex-col w-full md:w-[280px] border-l h-full transition-transform">
            <div class="flex flex-row flex-nowrap justify-between items-center mb-2 pl-4 pr-4 pt-4 md:pr-6 md:pt-6">
                <div class="text-base font-medium">Dernières activités</div>
                <div id="closeRecentActivitiesModalBtn"
                     class="md:hidden cursor-pointer active:scale-75 duration-100 will-change text-color-muted">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-x">
                        <path d="M18 6 6 18"/>
                        <path d="m6 6 12 12"/>
                    </svg>
                </div>
            </div>
            <div class=" h-full overflow-hidden">
                <div class="h-full flex flex-col gap-2 px-4 pb-6 overflow-y-auto">
                    {% for operation in recent_activities %}
                        {% include 'components/recent_activity.html' with operation=operation operation_type_titles=operation_type_titles now=now %}
                    {% empty %}
                        <div class="flex-1 flex flex-col gap-5 justify-center items-center h-full">
                            <svg xmlns="http://www.w3.org/2000/svg" width="68" height="68" viewBox="0 0 24 24"
                                 fill="none"
                                 stroke="#eaf89e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                 class="lucide lucide-clock-3">
                                <circle cx="12" cy="12" r="10"/>
                                <polyline points="12 6 12 12 16.5 12"/>
                            </svg>
                            <div class="text-base">Aucune activité</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script_tags %}
    <script>
       document.addEventListener("DOMContentLoaded", function () {
          const openRecentActivitiesModalBtn = document.getElementById("openRecentActivitiesModalBtn");
          const closeRecentActivitiesModalBtn = document.getElementById("closeRecentActivitiesModalBtn");
          const recentActivities = document.getElementById("recentActivities");

          openRecentActivitiesModalBtn.addEventListener(
             "click", function () {
                recentActivities.classList.remove("recentActivitiesHidden");
                recentActivities.classList.add("recentActivitiesShown");
             }
          );

          closeRecentActivitiesModalBtn.addEventListener("click", function () {
             recentActivities.classList.remove("recentActivitiesShown");
             recentActivities.classList.add("recentActivitiesHidden");
          });
       });
    </script>
{% endblock %}